
<head>
		<title><?php echo $lang->__($title); ?></title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="<?php echo $baseUrl; ?>js/skel.min.js"></script>
		<script src="<?php echo $baseUrl; ?>js/init.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
		<script type="text/javascript" src="http://balupton.github.com/jquery-syntaxhighlighter/scripts/jquery.syntaxhighlighter.min.js"></script>
		<script type="text/javascript">$.SyntaxHighlighter.init();</script>
		<noscript>
			<link rel="stylesheet" href="<?php echo $baseUrl; ?>css/skel.css" />
			<link rel="stylesheet" href="<?php echo $baseUrl; ?>css/style.css" />
			<link rel="stylesheet" href="<?php echo $baseUrl; ?>css/style-wide.css" />
			<link rel="stylesheet" href="<?php echo $baseUrl; ?>css/style-noscript.css" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>